### PR TITLE
F/5 new project for tests

### LINKED ISSUE #5: Add project for unit tests, integration tests, move sln file to the root folder

### PR DESCRIPTION
**Pull request by KorolS**
#5 Created projects for testing DG.Core and DG.HostApp projects with xUnit and Fluent Assertions frameworks.
Moved solution file to the DataGenies folder.

### CODE REVIEW

**Review by chesdenis — COMMENTED** [review]
To fix build please modify file https://github.com/chesdenis/DataGenies/blob/f/5-new-project-for-tests/.github/workflows/dotnetcore.yml inside this PR

**Comment by chesdenis** [comment]
it would be great if you add link to stylecop rules for tests csproj also:  <CodeAnalysisRuleSet>..\StyleCop.Analyzers.ruleset</CodeAnalysisRuleSet> you can find where it should be here: https://github.com/chesdenis/DataGenies/blob/develop/source/DG.HostApp/DG.HostApp.csproj

**Comment by KorolS** [comment]
> To fix build please modify file https://github.com/chesdenis/DataGenies/blob/f/5-new-project-for-tests/.github/workflows/dotnetcore.yml inside this PR

Done

**Comment by KorolS** [comment]
> it would be great if you add link to stylecop rules for tests csproj also:  ..\StyleCop.Analyzers.ruleset you can find where it should be here: https://github.com/chesdenis/DataGenies/blob/develop/source/DG.HostApp/DG.HostApp.csproj

Done

**Review by motpfofs — APPROVED** [review]

**Review by MihailRom — APPROVED** [review]

**Review by chesdenis — APPROVED** [review]

**Pull request merged**
